name: Deploy Project
on: push
jobs:
  Sync_Workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  Lint:
    needs: Sync_Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: eslint --ext .jsx --fix src
  Build:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: vite build
  Preview:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Preview
        run: vite preview
  Test:
    needs: Preview
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          vitest run
          echo "Deploying...." 
        
        
      
